
We'll first define the function used to simulate the networks.

```{r}
#' Read the edge definition and simulate the regulation ###
#'
#' @param size should be one of c("tiny","small","moderate","middle","large", "huge")
#' @param sample can be any positive number. 
#' @param noise  can be any positive number (for our study, we should try 0.25, 0.5, 0.75, 1, 1.5 and 2)  
network.simulation <- function(size, sample, noise, outputDir)
{
	dat <- read.csv(paste("../truth/", size,".csv",sep=""))

	dat <- dat[dat$Source != dat$Target,]
	dat[dat$Source > dat$Target,] <- dat[dat$Source > dat$Target,2:1]
	dat[dat$Source > dat$Target,]

	Gene <- union(dat$Source,dat$Target)
	nGene <- length(Gene)

	N <- dim(dat)[1]
	dat$regulation <- round(sign(rbinom(N, 1, 0.5) - 0.5)*rnorm(N,0.5,0.2) ,2)
	dat$type <- sign(dat$regulation)	

	write.csv(dat, paste("../truth/truth ",size,".csv",sep=""), row.names=F, quote=F)

	#### initiate the matrix expr to store the simulated expression level ####


	nSamp <- sample
	expr <- matrix(0,nGene, nSamp)
	rownames(expr) <- Gene
	colnames(expr) <- paste("S", 1:nSamp, sep="")

	sigma <- noise

	unknown <- unique(dat$Target)
	known <- setdiff(Gene, unknown)

	for(i in known)
	{
		expr[as.character(i),] <- rbinom(nSamp,1,0.5)*2 + rnorm(nSamp,0,sigma) - 1
	}

	while(length(unknown) > 0)
	{
		for(i in unknown)
		{			
			source <- as.character(dat$Source[dat$Target == i])
			if(all(source %in% known)) 
			{ 				
				val <- ifelse(rep(length(source) == 1,nSamp), 
					expr[as.character(source),]*dat[dat$Target == i,3] ,
					dat[dat$Target == i,3] %*% expr[as.character(source),])
				expr[as.character(i),] <- as.numeric(val > 0.0)*2-1 + rnorm(nSamp,0,sigma)
			 	known <- append(known,i)
				unknown <- setdiff(unknown, i) 
			}
		}	
	}
  	
	write.csv(round(expr,2), paste(outputDir, size,"nSamp", nSamp,"Sigma",noise,".csv", sep=""), row.names=T)

}
```

Now we'll generate the networks described in the existing variables `SIZE`, `NP`, and `NOISE` defined elsewhere.

```{r}
for(size in SIZE){
	for( sample in NP){
		for(noise in NOISE){
			network.simulation(size = size, sample = as.integer(sample), noise = as.numeric(noise), outputDir="../data/simulations/")
		}
	}
}
```